//! Chunk storage layout. Vanilla b1.7.3 dimensions: 16 wide, 128 tall, 16 deep.
//! Volume = 32768 cells. A chunk is a `Vec<u8>` of block ids (0 = air) with index
//! `(x<<11) | (z<<7) | y`, plus a `Nibbles` of block metadata with the same index; the chunks themselves
//! live in `world::chunks::ChunkManager`.

pub const W: usize = 16;
pub const H: usize = 128;
pub const D: usize = 16;
pub const VOLUME: usize = W * H * D;

/// Index of a cell within the chunk volume.
#[inline]
pub const fn idx(x: usize, y: usize, z: usize) -> usize {
    (x << 11) | (z << 7) | y
}

/// `NibbleArray`: 4 bits per cell, two cells to a byte (an even cell index is the low nibble), indexed like the
/// blocks (`idx`). A chunk's block metadata (`Chunk.data`: log species, wool colour, slab type, stair and door
/// facing, ...) lives in one, and its bytes are the McRegion `Data` tag as they are, so saving (M7) needs no
/// conversion. `Default` is the empty placeholder `mem::take` leaves behind; make a real one with `new`.
#[derive(Clone, Default, PartialEq, Eq, Debug)]
pub struct Nibbles(Vec<u8>);

impl Nibbles {
    pub fn new() -> Self {
        Self(vec![0; VOLUME / 2])
    }

    pub fn get(&self, x: usize, y: usize, z: usize) -> u8 {
        let i = idx(x, y, z);
        self.0[i >> 1] >> ((i & 1) * 4) & 15
    }

    /// Only the low 4 bits of `v` count (`NibbleArray.setNibble`).
    pub fn set(&mut self, x: usize, y: usize, z: usize, v: u8) {
        let i = idx(x, y, z);
        let s = (i & 1) * 4;
        let b = &mut self.0[i >> 1];
        *b = *b & !(15u8 << s) | (v & 15) << s;
    }

    pub fn bytes(&self) -> &[u8] {
        &self.0
    }

    /// The packed bytes back (a loaded save); the caller has checked the length.
    pub fn from_bytes(b: Vec<u8>) -> Self {
        debug_assert_eq!(b.len(), VOLUME / 2);
        Self(b)
    }
}

/// Blocks with no cube shape (tall grass, dead bush, flowers, mushrooms, snow layer, reeds). The
/// mesher skips them and physics walks through them until M14 gives them real models.
pub const fn is_plant(id: u8) -> bool {
    matches!(id, 31 | 32 | 37..=40 | 78 | 83)
}

/// Plants drawn as two crossed quads (render type 1): (half width, height) of the quads. Taken from each
/// block's `setBlockBounds`; vanilla draws a full-cell quad with a texture that is mostly transparent, and
/// until M14 has textures the bounds are the closest flat-colour stand-in.
// UNVERIFIED: shape only (bounds instead of the cut-out texture).
pub const fn cross_shape(id: u8) -> Option<(f32, f32)> {
    match id {
        37 | 38 => Some((0.2, 0.6)),   // flowers
        39 | 40 => Some((0.2, 0.4)),   // mushrooms
        31 | 32 => Some((0.4, 0.8)),   // tall grass, dead bush
        83 => Some((0.375, 1.0)),      // reeds
        _ => None,
    }
}

/// `Block.lightOpacity`: how much light a block eats (255 = fully opaque). Default is 255 for
/// opaque cubes and 0 for everything else; the overrides are `setLightOpacity` calls in Block.java
/// (water 3, lava 255, leaves 1, web 1, ice 3). Slabs (44) and wool (35) are not generated by
/// worldgen and read as opaque, which matches the 255 default for wool.
// UNVERIFIED: 44 (single slab) - Block.lightOpacity is set in the Block constructor before
// BlockStep.blockType exists, so vanilla may read 0 here.
pub const fn light_opacity(id: u8) -> u8 {
    match id {
        8 | 9 | 79 => 3,
        18 | 30 => 1,
        10 | 11 => 255,
        0 | 6 | 20 | 26..=29 | 31..=34 | 36..=40 | 50..=53 | 55 | 59 | 60 | 63..=72 | 75..=78 | 81 | 83 | 85 | 90 | 92..=94 | 96 => 0,
        _ => 255,
    }
}

/// `Block.lightValue` = `(int)(15.0F * setLightValue)`: block ids that emit light.
pub const fn light_value(id: u8) -> u8 {
    match id {
        10 | 11 | 51 | 89 | 91 | 95 => 15, // lava, fire, glowstone, jack-o-lantern, locked chest
        50 => 14,                          // torch (15/16)
        62 => 13,                          // lit furnace (14/16)
        90 => 11,                          // portal (12/16)
        74 | 94 => 9,                      // glowing redstone ore, lit repeater (10/16)
        76 => 7,                           // redstone torch (0.5)
        39 => 1,                           // brown mushroom (2/16)
        _ => 0,
    }
}

/// `WorldProvider.generateLightBrightnessTable`: light level 0..=15 -> brightness 0.05..=1.0.
pub fn brightness(level: u8) -> f32 {
    let f = 1.0 - level as f32 / 15.0;
    (1.0 - f) / (f * 3.0 + 1.0) * (1.0 - 0.05) + 0.05
}

/// `Chunk.heightMap` for one chunk, indexed `z << 4 | x`: the y of the first cell, scanning down from
/// the top, whose block below it is not fully transparent (`generateHeightMap`).
pub fn height_map(blocks: &[u8]) -> [u8; 256] {
    let mut h = [0u8; 256];
    for x in 0..W {
        for z in 0..D {
            let base = idx(x, 0, z);
            let mut y = H - 1;
            while y > 0 && light_opacity(blocks[base + y - 1]) == 0 {
                y -= 1;
            }
            h[z << 4 | x] = y as u8;
        }
    }
    h
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Same layout as the Java `NibbleArray`: low nibble first, cell index `x << 11 | z << 7 | y`, neighbours untouched.
    #[test]
    fn nibbles_pack_like_java() {
        let mut n = Nibbles::new();
        n.set(0, 0, 0, 5);
        n.set(0, 1, 0, 9); // cell 1: the high nibble of byte 0
        n.set(15, 127, 15, 0xAB); // the last cell; only the low 4 bits count
        assert_eq!(n.bytes()[0], 0x95);
        assert_eq!(n.bytes()[VOLUME / 2 - 1], 0xB0);
        assert_eq!((n.get(0, 0, 0), n.get(0, 1, 0), n.get(15, 127, 15), n.get(1, 0, 0)), (5, 9, 11, 0));
        n.set(0, 0, 0, 0);
        assert_eq!(n.bytes()[0], 0x90);
    }
}
