[package]
name = "mc-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "mc_android"
crate-type = ["cdylib"]

[dependencies]
mc-core = { path = "../mc-core" }
android-activity = { version = "0.6", features = ["native-activity"] }

[package.metadata.android]
package = "dev.mcrs.b173"
apk_name = "MinecraftB173Rust"
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]

[package.metadata.android.sdk]
min_sdk_version = 24
target_sdk_version = 34

[package.metadata.android.application]
label = "MC b1.7.3 Rust"
