#!/usr/bin/env python3
"""Regenerates mc-rs/src/render/font.rs (font/default.png glyphs + FontRenderer widths) and
mc-rs/src/world/names.rs (Block/Item setBlockName/setItemName + lang/en_US.lang). Run from the repo root;
needs `unzip` and Pillow. Inputs: minecraft/jars/deobfuscated.jar, minecraft/src/net/minecraft/src/{Block,Item}.java."""
import re, subprocess, io
from PIL import Image
jar = "minecraft/jars/deobfuscated.jar"
rd = lambda p: subprocess.check_output(["unzip", "-p", jar, p])
src = "minecraft/src/net/minecraft/src/"

# Font: FontRenderer.<init>: width = last non-empty column of the 8x8 cell + 2, space = 4.
im = Image.open(io.BytesIO(rd("font/default.png"))).convert("RGBA")
rows, wid = [], []
for c in range(32, 127):
    ox, oy = c % 16 * 8, c // 16 * 8
    on = lambda x, y: im.getpixel((ox + x, oy + y))[0] > 0 and im.getpixel((ox + x, oy + y))[3] > 0
    rows.append([sum(1 << x for x in range(8) if on(x, y)) for y in range(8)])
    last = next((x for x in range(7, -1, -1) if any(on(x, y) for y in range(8))), 7 if c != 32 else 2)
    wid.append(4 if c == 32 else last + 2)
with open("mc-rs/src/render/font.rs", "w") as f:
    f.write("//! GENERATED by tools/gen_names.py from the b1.7.3 `font/default.png`; do not edit.\n"
            "//! `GLYPHS[c - 32][row]` bit x = pixel x (bit 0 left); `WIDTH` = `FontRenderer.charWidth`.\n")
    f.write("pub const GLYPHS: [[u8; 8]; 95] = [\n" + "".join(f"    {r},\n" for r in rows) + "];\n")
    f.write("pub const WIDTH: [u8; 95] = " + str(wid) + ";\n")

# Names.
lang = {}
for l in rd("lang/en_US.lang").decode("utf-8").splitlines():
    if "=" in l and not l.startswith("#"):
        k, v = l.split("=", 1); lang[k.strip()] = v.strip()
out = {}
for stmt in open(src + "Block.java", encoding="utf-8").read().split(";"):
    m = re.search(r"new \w+\((\d+)[^;]*?\.setBlockName\(\"(\w+)\"\)", stmt, re.S)
    if m and f"tile.{m[2]}.name" in lang: out[int(m[1])] = lang[f"tile.{m[2]}.name"]
for stmt in open(src + "Item.java", encoding="utf-8").read().split(";"):
    m = re.search(r"new \w+\((\d+)[^;]*?\.setItemName\(\"(\w+)\"\)", stmt, re.S)
    if m and f"item.{m[2]}.name" in lang: out[256 + int(m[1])] = lang[f"item.{m[2]}.name"]
dye = "black red green brown blue purple cyan silver gray pink lime yellow lightBlue magenta orange white".split()
wool = [lang[f"tile.cloth.{dye[~m & 15]}.name"] for m in range(16)]  # ItemCloth: ~damage & 15
inks = [lang[f"item.dyePowder.{d}.name"] for d in dye]
slab = [lang[f"tile.stoneSlab.{s}.name"] for s in "stone sand wood cobble".split()]
res = {}  # Block.setResistance(r) stores r * 3 (setHardness only raises it to h * 5, which the port computes from `dig::hardness`)
for stmt in open(src + "Block.java", encoding="utf-8").read().split(";"):
    m = re.search(r"new \w+\((\d+)[^;]*?\.setResistance\(([\d.]+)F?\)", stmt, re.S)
    if m: res[int(m[1])] = float(m[2]) * 3
q = lambda l: "[" + ", ".join(f'"{s}"' for s in l) + "]"
with open("mc-rs/src/world/names.rs", "w") as f:
    f.write("//! GENERATED by tools/gen_names.py from `Block`/`Item` `setBlockName`/`setItemName` and `lang/en_US.lang`.\n")
    f.write("pub const NAMES: &[(u16, &str)] = &[\n" + "".join(f'    ({i}, "{n}"),\n' for i, n in sorted(out.items())) + "];\n")
    f.write(f"pub const WOOL: [&str; 16] = {q(wool)};\npub const DYE: [&str; 16] = {q(inks)};\npub const SLAB: [&str; 4] = {q(slab)};\n")
    f.write(f'pub const CHARCOAL: &str = "{lang["item.charcoal.name"]}";\n')
with open("mc-rs/src/world/names.rs", "a") as f:
    f.write("/// `Block.blockResistance` where `setResistance` was called (ids < 256, sorted); elsewhere it is hardness x 5.\n")
    f.write("pub const RESIST: &[(u8, f32)] = &[" + ", ".join(f"({i}, {r!r})" for i, r in sorted(res.items()) if i < 256) + "];\n")
print(len(out), "names", len(res), "resistances")
