plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.bgame.voxel'
    compileSdk 34

    defaultConfig {
        applicationId "dev.bgame.voxel"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug // sideload-ready; replace with your own key for publishing
        }
    }

    sourceSets {
        main { jniLibs.srcDirs = ['src/main/jniLibs'] }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
